main: com.vinkas.testPlugin.TestPlugin
name: TestPlugin
version: '1.0'
description: A test plugin
author: vinkas
commands:
  boss1:
    description: spawns boss
    aliases: boss
  necron:
    description: necron
  storm:
    description: storm
  itemsgui:
    description: opens inventory
    aliases: ci
